### PR TITLE
Rename PluginManager setting

### LINKED ISSUE #35: Modify setting to close GE
There's a setting to close GE as soon as PM is started:
image

IMHO, it is valid to have an option to avoid this popup when a user installs a plugin:
image

However, the current implementation seems a bit "exaggerated". It always shuts down GE straight away when PM is started, even if the user doesn't install any plugin. Maybe I just clicked the plugin by accident....

I propose to change this into something like "Automatically close Git Extensions when installing plugins (don't ask for confirmation)". The default value should remain `false`.

### PR DESCRIPTION
**Pull request by ivangrek**
fixes #35

### CODE REVIEW

**Review by RussKie — COMMENTED** [review]
👍

**Comment by ivangrek** [comment]
Not sure if we can restart processes gracefully.

**Review by mast-eu — CHANGES_REQUESTED** [review]
Sorry, I went through the use cases and I think this PR is not yet working as it should.

**Use case 1:** Set `Automatically close Git Extensions when installing plugins` = FALSE and try to uninstall a plugin which is used by a second GE instance.

**What happens:** 

- The PM does not show any dialog 
- All GE instances remain open
- Plugin not removed (plus, I get a popup from Windows User Account Control)

**What should happen:** 

- The PM shows the dialog image
- According to the selection all GE instances are either closed or remain open
- Plugin removed (if select to close GE)

**Use case 2:** Set `Automatically close Git Extensions when installing plugins` = TRUE and try to uninstall a plugin which is used by a second GE instance.

**What happens:**

- The PM does show the dialog 
image
- According to the selection all GE instances are either closed or remain open
- Plugin removed (if select to close GE)

**What should happen:** 

- No dialog is shown 
- All Git Extensions instances are closed
- Plugin removed

**Comment by ivangrek** [comment]
Yes, only works for installations.

**Comment by mast-eu** [comment]
> Not sure if we can restart processes gracefully.

I think we discussed this some time ago (don't remember where and when). Restarting gracefully would at least include to reopen the repos I had opened (might be more than just 1 instance of GE), potentially also restore the window positions and other stuff.
Some internal states (selected branch/commit, filters, whatever) would probably be lost anyhow. Therefore I wouldn't bother with trying to restore something that would likely be incomplete.

**Comment by ivangrek** [comment]
This requires a full session save function, if there is none.

**Comment by ivangrek** [comment]
GitExtensions.exe --restore-last-session

**Comment by RussKie** [comment]
In context of several instances what does this mean?

**Comment by ivangrek** [comment]
By process number in the order of the launches.

**Comment by ivangrek** [comment]
LIFO

Open 1, 2, 3;
Close 2, 1, 3.
Reopen 3, 1, 2.

Like a stack. Looks like this.
Updating the top of the stack when closing.

**Comment by ivangrek** [comment]
> Use case 1: Set Automatically close Git Extensions when installing plugins = FALSE.
> The PM shows the dialog

> Set Automatically close Git Extensions when installing plugins = TRUE
> No dialog is shown

It is correct?

image

I think it works.

**Comment by mast-eu** [comment]
> > Use case 1: Set Automatically close Git Extensions when installing plugins = FALSE.
> > The PM shows the dialog
> 
> > Set Automatically close Git Extensions when installing plugins = TRUE
> > No dialog is shown
> 
> It is correct?
> 
I'm not sure I understood you correctly. Is your doubt about when the close dialog should be shown and when not?

When `Set Automatically close Git Extensions when installing plugins` is _not checked_, I expect GE to _not close automatically_. Instead, it should ask me (i.e. showing the dialog):

When `Set Automatically close Git Extensions when installing plugins` _is checked_, I expect GE to _close automatically_. Hence, the dialog is not needed, since I have nothing to choose/confirm.

> Yes, only works for installations.

Maybe we should not focus primarily on the install part. IMHO, uninstall is more critical, since it can easily fail. 
Just open 2 instances of GE, run a plugin in one instance and try to uninstall the same plugin from the second instance. This will fail, since the DLL cannot be deleted while it is used.
That's why all instances need to be closed before modifying the plugins via Plugin Manager.

**Comment by ivangrek** [comment]
I was confused by "Confirmation".
If this is a confirmation, then nothing should happen after the cancellation, but it is not.
Because closing GE instances is a necessity.

**Comment by ivangrek** [comment]
Only confused by the behavior after canceling the confirmation.

**Comment by mast-eu** [comment]
> behavior after canceling the confirmation.

All GE instances remain open, plugin is not installed/updated/removed.

**Pull request closed without merging**
