### PR TITLE
Initial code migration from maraf/GitExtensions.PluginManager.

### PR DESCRIPTION
**Pull request by maraf**
Includes replacement of author.
Removal of testing nuget packages.

### CODE REVIEW

**Comment by maraf** [comment]
Sure, no problem. I'm using two packages here:
`Neptuo` - Set of basic utils, argument checking etc.
`Neptuo.Observables` - Base classes for MVVM.

**Comment by mast-eu** [comment]
I pushed a change to make the the PluginManager (GE plugin) the default startup project and make it run directly with hitting F5. Please have a look.

**Comment by mast-eu** [comment]
@maraf : If you approve the changes I've pushed, do you want to take the honor of merging the first PR? :wink:

**Comment by RussKie** [comment]
🎉

**Comment by maraf** [comment]
With greatest pleasure.

**Pull request merged**
