### PR TITLE
Enable test signing policy

### PR DESCRIPTION
**Pull request by RussKie**

### CODE REVIEW

**Comment by RussKie** [comment]
@mast-eu @maraf the test policy appears to be working
image

We'll need to create a release policy and hook it up for a official release builds

**Comment by mast-eu** [comment]
Test signing already looks good to me. I checked that the` .nupkg` file tself, as well as the contained `*.dll` and `*.exe` files, are all correctly signed with the test certificate.

image

> We'll need to create a release policy and hook it up for a official release builds

I'd mimic GE here as well. Every time we commit to a branch `release/*` the artifact gets automatically downloaded from appveyor.com to signpath.io and submitted for signing with the release certificate.

**Comment by RussKie** [comment]
I can't get it to work yet.
though I think I'm almost there

**Comment by RussKie** [comment]
Ok, after a lot of back and forth, multiple chats with SignPath and AppVeyor tech support, I got the signing working
image

One thing I don't particular like is the chosen numbering strategy - `...0.9.0-build0061+423dc359aa...`, I think it should be `...0.9.0.61-423dc359aa...`.

**Comment by RussKie** [comment]
The signing is turned off by default and is controlled by a env var at the AppVeyor end

**Comment by mast-eu** [comment]
> One thing I don't particular like is the chosen numbering strategy - `...0.9.0-build0061+423dc359aa...`, I think it should be `...0.9.0.61-423dc359aa...`.

Versioning scheme has been recently changed in #18. The artifact is now named 
`GitExtensions.PluginManager.1.0.0.62-RC1.nupkg`.

**Comment by RussKie** [comment]
Great, thanks!

**Comment by mast-eu** [comment]
Sorry, I didn't realize it earlier. Please consider also what I wrote in https://github.com/gitextensions/gitextensions.pluginmanager/issues/17#issuecomment-514091022 for the signing policies.

**Comment by RussKie** [comment]
I responded in #17.
Feel free to merge or close at will.

**Comment by mast-eu** [comment]
> Feel free to merge or close at will.

I'll merge this PR as is. 
The remaining work on signing policies can be done in #17.

**Pull request merged**
