### PR TITLE
Enable auto update

### PR DESCRIPTION
**Pull request by mast-eu**
## Proposed change

* Re-enable the self-update functionality that has been temporarily disabled in #24.
* Add the license file to the NuGet package. This has no functional impact, but is just to avoid warnings when checking the package.

### CODE REVIEW

**Comment by mast-eu** [comment]
@maraf : I tried to test this with the following setup:

1. Create a local test feed with an "artificial" package `PluginManager v2.0.0` (just modified version number and re-built the package locally).
2. Launch the PM built from this PR (i.e. with auto-update enabled as in the original version).
3. Add the test feed from step 1) to the list of package sources and search it for packages.
 
-> it finds the `PluginManager v2.0.0` as expected, but I cannot install it. The button is always grayed out.
image

First I thought I messed up the local feed somehow. Thus I added another package (`GitExtensions.SVN`) to it. This one can be installed and updated as expected. 
image
Therefore I think there must be some problem specific to the self-update mechanism, but I fail to see it. Any hints?
For cross-checking, here is the test feed that I created and used for testing: [TestFeed.zip](https://github.com/gitextensions/gitextensions.pluginmanager/files/3773942/TestFeed.zip)

**Comment by mast-eu** [comment]
You're right that it's an update, not a fresh install. I should have included other screenshots.

However, the PM is not shown neither in the "Updates" tab:
image

nor in the "Installed" tab:
image

The `packages.config` file looks ok to me:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="GitExtensions.PluginManager" version="0.0.0.1" />
  <package id="GitExtensions.SVN" version="0.2.1.24" />
</packages>
```

The log file confirms that the packages were found as expected:
```
27/10/2019 00:00:11 root.Search(DEBUG)

Searching - user text:''; feed query:' tags:GitExtensions'.

27/10/2019 00:00:11 root.Search(DEBUG)

Loading page '0'.

27/10/2019 00:00:11 root.Search(DEBUG)

Searching in 'file:///C:/Users/Martin/Desktop/TestFeed'.

27/10/2019 00:00:11 root.Search(DEBUG)

Found 'GitExtensions.PluginManager.2.0.0.1'.

27/10/2019 00:00:11 root.Search(DEBUG)

Package added.

27/10/2019 00:00:11 root.Search(DEBUG)

Found 'GitExtensions.SVN.0.2.3.26'.

27/10/2019 00:00:11 root.Search(DEBUG)

Package added.

27/10/2019 00:00:11 root.Search(DEBUG)

Search completed. Found '2' items.
```
So I expected to be able to update to PM 2.0.0, but that's not working. Or at least I cannot figure out how to make it work.

**Comment by maraf** [comment]
I'll take a look.

**Comment by maraf** [comment]
Well, update works in a quite complicated way...

### Quick solution:
Place package with PM in currently installed version in the test feed.

image

image

### How it works
Aft first, update uses `NuGetInstallService.GetInstalledAsync` to get list of installed packages. The source of truth is `packages.confg`, but there is not enough information, so it also uses currently selected feed(s) to fetch all data it requires. This is the problem here. If user selects feed without current version of installed package, **it just ignores that package**. 

Than it uses selected feed(s) to look for newer versions on installed packages and offers udpates.

In a production environment it works quite good, because package X is in feed A, and also the newer version is in the same feed.

[failed.log](https://github.com/gitextensions/gitextensions.pluginmanager/files/3775786/failed.log)
[success.log](https://github.com/gitextensions/gitextensions.pluginmanager/files/3775787/success.log)

**Comment by mast-eu** [comment]
> Place package with PM in currently installed version in the test feed.

Confirm it's working. Thanks.

> If user selects feed without current version of installed package, **it just ignores that package**.

This means that the package for v1.1.0 already needs to be published on nuget.org. Otherwise any later self-update would not work. 
That's not a problem. Just something to be aware of while preparing the release.

**Pull request merged**
