### PR TITLE
Migration to .NET 5

### LINKED ISSUE #57: Support .NET
Git Extensions@master has been migrated to .NET 5.0. Once .NET 6.0 is released the app will be migrated to it.
The plugin manager is currently can't be used with the dev version of the app as it is targeting .NET Framework.

### PR DESCRIPTION
**Pull request by maraf**
- Replaced costura with .NET single file publish.
- Fixed package source ordering in Nuget.PackageManagement-v5.11.0.
- Updated release script.

Fixes #57.

### CODE REVIEW

**Review by RussKie — APPROVED** [review]
Looks sensible :shipit:

**Comment by RussKie** [comment]
I'm testing the .NET 5.0 release, and the Plugin Manager is failing to start with the following error:
```
Description: A .NET application failed.
Application: PackageManager.UI.exe
Path: D:\Development\gitextensions\artifacts\Release\publish\GitExtensions-Portable-33.33.33.0-0af3f84d3\UserPlugins\GitExtensions.PluginManager\PackageManager\PackageManager.UI.exe
Message: The application to execute does not exist: 'D:\Development\gitextensions\artifacts\Release\publish\GitExtensions-Portable-33.33.33.0-0af3f84d3\UserPlugins\GitExtensions.PluginManager\PackageManager\PackageManager.UI.dll'.
```

It looks like it is looking for PackageManager.UI.dll, and there's only a PackageManager.UI.exe....

**Comment by RussKie** [comment]
You can grab build artifacts here: https://ci.appveyor.com/project/gitextensions/gitextensions-pluginmanager/builds/41359003, or use the branch if you want to build it locally: https://github.com/gitextensions/gitextensions/tree/msi

**Comment by maraf** [comment]
@RussKie Are you using MSI or portable? Because with portable from the link about it seems the PM is working (it shows an error with reading settings, but the PM starts and works)

**Comment by maraf** [comment]
💡 Also, the installer and portable still contains an previous PM version (1.1.0.109).
So, I think we need to first release the PM v2.0 and than we can test the GE installer. Correct?

**Comment by RussKie** [comment]
I built the msi locally having downloaded the latest version of the PM
manually.
Then installed the msi.

**Comment by maraf** [comment]
I probably found the problem. The build on AppVeyor doesn't work as locally.

image

Size of these artifacts should be about 4MB. 

The problem is with single file publish of PackageManager UI. 
It seems it ignores the [publish profile](https://github.com/gitextensions/gitextensions.pluginmanager/blob/1132651c7e8dd73c8ee9762523231c71fd5543f9/tools/Prepare-Release.ps1#L15).

**Pull request merged**
