### PR TITLE
Resize app icon

### LINKED ISSUE #33: Icon too small
The currently used icon is too small (16*16 px) for being properly visualized in the taskbar and in thumbnail previews. 
See in comparison to GE:

image

image

Ideally, the icon should be available in 256*256 px, to support high-resolution displays.

### PR DESCRIPTION
**Pull request by oriash93**
Fixes #33

### CODE REVIEW

**Comment by RussKie** [comment]
Have you tested this at different scaling factors? E.g. 100%, 150%, 200%.

Please add screenshots and explain what you did to the icon.

Thank you

**Review by mast-eu — APPROVED** [review]
When I wrote the issue, I was thinking of searching/creating a new icon rather than upscaling the existing. 
However, the upscaled version still looks much better than the current one. So for me the PR is fine.

**Comment by oriash93** [comment]
> Please add screenshots and explain what you did to the icon.

I simply upscaled it with a professional tool.

> Have you tested this at different scaling factors? E.g. 100%, 150%, 200%.

Screenshots:
150%


125%


100%

**Comment by RussKie** [comment]
Works for me, thanks.
Martin your call.

**Comment by mast-eu** [comment]
Thank you.

**Comment by oriash93** [comment]
You're welcome!
One small thing - can you please mark this PR or repo as eligible for hacktoberfest?

**Pull request merged**
